### ISSUE TITLE
Determine GSM and GPRS Status

### ISSUE THREAD

**Issue by alvarolb** [arduino-libraries/MKRGSM#15]
I am working on a client for [Thinger.io](https://thinger.io) that requires persistent connection to a socket, even on tower cells changes. I am implementing the reconnection mechanism on socket disconnections, but I did not found an actual way to determine the current GSM or GPRS status. So, one question is, once attached to GSM/GPRS, it may require re-attach again if something goes wrong, like signal loss? or is it handled automatically by the ublox module? 

If re-attach is required, it may be interesting to determine the current GPRS or GSM status, to avoid a complete module restart.

Thanks!

**Comment by FrancMunoz** [comment]
Hi @alvarolb!

To debug status I've created a Faraday Jail to simulate losing signal.

I used to read client or server and when an error returned reconnect. If you are only using client just send `AT+UPSDA=0,3` and client will work again. For server, I created a function called `connectGSM `and called every time an error is reported calling available (the project is very stable). But... This is an ugly way to achieve this...

Right now, I've asked @sandeepmistry to include URC callback to ModemClass (you can see it #16 ). And I'm looking for in [u-blox AT Commands](https://www.u-blox.com/en/files/u-blox-cellularatcommanualubx-13002752pdf) whether SARA sends any URC when this happens and then reconnect both client and server.

All in all, should wait what @sandeepmistry  has to say, because he has more knowledge than me about that.

Hope this helps!

**Comment by w3p706** [comment]
I encounter the similar problems. After 1.5 days (only running UDP) I receive the following to messages from the modem:

+UUPSDD: 0
+UUSOCL: 0

UUPSDD: Context deactivation by the network – A URC indicates PDP context #0 is closed by the
network.
UUSOCL: Socket close

All the following UDP requests don't succeed.

Neither the GPRS nor the UDP class is handling this case as far as I can see.

I will have to look further how this case could be handled. Currently there is no way to detect if still connected if only using UPD, or is it?

**Comment by sandeepmistry** [comment]
Hi everyone, pull request #19 has a proposal for this, however it's still work in progress.

Any early feedback that you have on the changes would be appreciated though.

**Comment by Rocketct** [comment]
Hi @alvarolb you could use the code in the proposal of @sandeepmistry to retrieve the status of the GSM connection and of the GPRS, moreover is not required a reset of the board but a simple call to the attachGPRS function for restore the connection if available.

**Comment by sandeepmistry** [comment]
Closed via PR #19.

Thanks for everyone's feedback!
