### ISSUE TITLE
Use of HEX MODE as base syntax

### ISSUE THREAD

**Issue by zz-zsys** [arduino-libraries/MKRGSM#38]
This is basically more of understanding question rather than issue.

The hex mode configuration is enabled by default through  AT+UDCONF=1,1 command.
As example, the GSMClient write command will change the the incoming data as HEX data to be sent.

In the datasheet under +USOWR, it states that 

Number of data bytes to write:
• Base syntax normal mode: range 1-1024
• Base syntax HEX mode: range 1-512
• Binary extended syntax: range 1-1024

Due to this reason the chunk size is limited to 256 as the maximum range is 512. 

Is there any reason to use HEX MODE rather than normal mode to send than the socket data?
Due to my understanding with normal mode, you can send up to 1024 characters. Am I right?

Thanks, ZZ

**Comment by sandeepmistry** [comment]
Hi @zz-zsys,

> Is there any reason to use HEX MODE rather than normal mode to send than the socket data?

The AT command + response parser could be kept simpler and more consistent to start. However, if there's a good reason to make it support binary in the future this can be looked at.

> Due to my understanding with normal mode, you can send up to 1024 characters. Am I right?

That's correct.


I'm going to close this for now, because the original question was answered. However, feel free to re-open if I didn't fully answer the question.
