### ISSUE TITLE
Multipart SMS receive

### ISSUE THREAD

**Issue by Milan991** [arduino-libraries/MKRGSM#65]
Is there a plan for creating function for multipart SMS message receive?
I done it by using current message read function, there is some troubles with unnecessary CR/LF at the and of first part of message. 
It would be nice if that is all done in one library function.

Thank you in advance.

**Comment by sandeepmistry** [comment]
Hi @Milan991,

Could you please clarify what a multipart SMS message is, and also provide a simple sketch and detailed steps to reproduce this condition. Thanks.

**Comment by Milan991** [comment]
@sandeepmistry You can reproduce this condition by sending SMS message that have more than 160 characters from your Phone to MKRGSM. In that case message is separated into two messages, so I've to concatenate it into one String. In that case there is also issue with CR/LF at the and of first message.

**Comment by Rocketct** [comment]
Hi @Milan991, thank you for open this issue, but the module of the MKRGSM, SARA-U201, doesn't support the concatenated SMS and the AT commands (AT+UCMGL for example) required to read the SMS bigger then 160 characters, this make impossible understand if two message are concateneted or not, because when the module receive a concatenated SMS is not able to read the first part of the message where are stored the data related to sequence number and read it as a single message bigger 151 characters.

**Comment by Milan991** [comment]
Hi @Rocketct, if this is situation right now I will leave my code with my workaround. Thank you. Closing this issue.
